// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd_8FbWJatldjP5__2ixP5KftBcSIj-iM',
    appId: '1:927432211791:web:5a60df9fcfaadab0ff193a',
    messagingSenderId: '927432211791',
    projectId: 'swachhata-app1',
    authDomain: 'swachhata-app1.firebaseapp.com',
    storageBucket: 'swachhata-app1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgV917TLKEk650eLMlSVaSyisYaRPuhuA',
    appId: '1:927432211791:android:3f5754e6fdb66893ff193a',
    messagingSenderId: '927432211791',
    projectId: 'swachhata-app1',
    storageBucket: 'swachhata-app1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfYegUwAPXzgLCPHfuyUXarZZgf0XJFwI',
    appId: '1:927432211791:ios:c1605fe7e4b90c5fff193a',
    messagingSenderId: '927432211791',
    projectId: 'swachhata-app1',
    storageBucket: 'swachhata-app1.firebasestorage.app',
    iosBundleId: 'com.example.swachhataApp',
  );
}
